[build]
  base = "frontend"
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = ""

[context.branch-deploy]
  command = ""
